name: App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install dependencies
      run: ./scripts/bootstrap.sh

    - name: Run tests
      run: ./scripts/test.sh

    - name: Upload reports
      run: npx codecov
