# Generates the static page under the `pr` subdirectory inside the
# `ghpages` branch on every PR open/reopen/synchronize/close.

name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

env:
  PREVIEW_BRANCH: ghpages
jobs:
  deploy-preview:
    # pr-preview-action v1 cannot deploy previews for PRs from forks
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: Set up Git
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"

      - name: Install and Build
        if: github.event.action != 'closed'
        run: |
          ./scripts/bootstrap.sh
          yarn install --frozen-lockfile
          yarn run ghpages:build

      # Reference: https://github.com/rossjrw/pr-preview-action
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        id: preview-step
        with:
          source-dir: ./ghpages
          umbrella-dir: pr
          preview-branch: ${{ env.PREVIEW_BRANCH }}
          comment: false

      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.preview-step.outputs.deployment-action == 'deploy'
        with:
          header: pr-preview
          message: |
            [PR Preview Action](https://github.com/rossjrw/pr-preview-action) ${{ steps.preview-step.outputs.action-version }}
            :---:
            | <p></p> :rocket: View preview at <br> ${{ steps.preview-step.outputs.preview-url }} <br><br>
            | <h6>Built to branch [`${{ env.PREVIEW_BRANCH }}`](${{ github.server_url }}/${{ github.repository }}/tree/${{ env.PREVIEW_BRANCH }}) at ${{ steps.preview-step.outputs.action-start-time }}. <br> Preview will be ready when the [GitHub Pages deployment](${{ github.server_url }}/${{ github.repository }}/deployments) is complete. <br><br> </h6>

      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.preview-step.outputs.deployment-action == 'remove'
        with:
          header: pr-preview
          message: |
            [PR Preview Action](https://github.com/rossjrw/pr-preview-action) ${{ steps.preview-step.outputs.action-version }}
            :---:
            Preview removed because the pull request was closed.
            ${{ steps.preview-step.outputs.action-start-time }}
